name = "outbound-messages"
main = "index.js"
compatibility_date = "2023-01-01"
account_id = "1e230692e8529617e34ee5ca900acae1"

[vars]
sunco_app_id = ''
sunco_integration_id = ''
sunco_key_id = ''
sunco_secret_key = '' 
zendesk_admin_email = ''
zendesk_token = ''
zendesk_domain = ''

# This secret_key one should be encrypted in the UI!