name = "outbound-messages"
main = "index.js"
compatibility_date = "2023-01-01"

[vars]
sunco_app_id = ""
sunco_integration_id = ""
sunco_key_id = ""
zendesk_admin_email = ""
zendesk_domain = ""
sunco_secret_key = '' 
zendesk_token = ''

# Replace with your values
# This secret_key and zendesk_token should be encrypted in the UI!